# -*- coding: utf-8 -*-
"""RecomendationSystem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WCyBf4xzzg3eRhZBGMbSRIsQsbdKukTW
"""

from google.colab import files
upload = files.upload()

! ls

import pandas as pd
df = pd.read_csv('DiseaseData.csv')

df.head()

# df = df.drop('Index',1)

df.set_index('Month',inplace=True)

df[:5].plot(figsize=(5,5),kind='bar')

df.head()

df[:10]

target_data = df.shift(-1)  # Will use -1 if needed
target_data.head()

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df = scaler.fit_transform(df)
target_data = scaler.fit_transform(target_data)

target_data[:10]

# from keras.preprocessing.sequence import  TimeseriesGenerator
# generator = TimeseriesGenerator(df,target_data,length=1,batch_size=10)

# import numpy as np
# df=df.reshape(1,-1,1)

df[5,:]

from keras.models import Sequential,Model
from keras.layers import GRU,Dense,Dropout

model = Sequential()
# model.add(GRU(256,return_sequences=True,input_shape=(None,1,)))
# model.add(Dropout(0.2))
# model.add(GRU(512,return_sequences=True))
# model.add(GRU(1024,return_sequences=False))
model.add(Dense(256,activation='relu',input_shape=(10,)))
model.add(Dense(512,activation='relu'))
model.add(Dense(1024,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10,activation='relu'))

model.summary()

model.compile(optimizer='adam',loss='mse',metrics=['acc'])

# df = df.reshape(1,-1,10)

model.fit(df,target_data,validation_split=0.12,batch_size=10,epochs= 100)

# model.fit_generator(generator,epochs=100)
df[1,:].shape

prediction=model.predict(df[5,:].reshape(1,-1))

scaler.inverse_transform(prediction)

model.save('RecommandationSystem.h5')

import pickle

with open("Scaler(RecommationSystem)",'wb') as file:
  pickle.dump(scaler,file)

df[5,:]